export type CategorySlug =
  | "finance"
  | "shopping"
  | "food"
  | "travel"
  | "education"
  | "productivity"
  | "developer"
  | "entertainment";

export type BenefitType = "cashback" | "discount" | "free-month" | "credits" | "reward";

export type Trust = "verified" | "trusted" | "new" | "expiring";

export type Referral = {
  id: string;
  service: string;
  initials: string;
  category: CategorySlug;
  benefit: string;
  benefitType: BenefitType;
  summary: string;
  details: string;
  conditions: string[];
  code: string;
  isLink: boolean;
  tags: string[];
  postedBy: { username: string; name: string; initials: string; trustScore: number };
  postedAgo: string;
  postedOn: string;
  copies: number;
  popularity: number;
  trust: Trust[];
  expires: string;
  status: "active" | "past";
};

export const categories: {
  slug: CategorySlug;
  name: string;
  blurb: string;
  count: number;
  accent: string;
  soft: string;
  emoji: string;
}[] = [
  {
    slug: "finance",
    name: "Finance & Payments",
    blurb: "Banks, UPI apps, brokers, cards",
    count: 128,
    accent: "text-leaf",
    soft: "bg-leaf-soft",
    emoji: "₹",
  },
  {
    slug: "shopping",
    name: "Shopping",
    blurb: "Marketplaces, fashion, electronics",
    count: 94,
    accent: "text-grape",
    soft: "bg-grape-soft",
    emoji: "🛍",
  },
  {
    slug: "food",
    name: "Food & Delivery",
    blurb: "Delivery apps, cloud kitchens, groceries",
    count: 76,
    accent: "text-rose",
    soft: "bg-rose-soft",
    emoji: "🍜",
  },
  {
    slug: "travel",
    name: "Travel",
    blurb: "Flights, stays, cabs and rentals",
    count: 61,
    accent: "text-sky",
    soft: "bg-sky-soft",
    emoji: "✈",
  },
  {
    slug: "education",
    name: "Education",
    blurb: "Courses, test prep, certifications",
    count: 48,
    accent: "text-amber",
    soft: "bg-amber-soft",
    emoji: "✎",
  },
  {
    slug: "productivity",
    name: "Productivity",
    blurb: "Notes, tasks, design and AI tools",
    count: 57,
    accent: "text-grape",
    soft: "bg-grape-soft",
    emoji: "◎",
  },
  {
    slug: "developer",
    name: "Developer Tools",
    blurb: "Hosting, databases, monitoring",
    count: 39,
    accent: "text-sky",
    soft: "bg-sky-soft",
    emoji: "⌘",
  },
  {
    slug: "entertainment",
    name: "Entertainment",
    blurb: "Streaming, music, gaming",
    count: 44,
    accent: "text-rose",
    soft: "bg-rose-soft",
    emoji: "▶",
  },
];

export const categoryBySlug = Object.fromEntries(categories.map((c) => [c.slug, c])) as Record<
  CategorySlug,
  (typeof categories)[number]
>;

export const benefitTypes: { value: BenefitType; label: string }[] = [
  { value: "cashback", label: "Cashback" },
  { value: "discount", label: "Discount" },
  { value: "free-month", label: "Free month" },
  { value: "credits", label: "Credits" },
  { value: "reward", label: "Reward" },
];

const p = (username: string, name: string, initials: string, trustScore: number) => ({
  username,
  name,
  initials,
  trustScore,
});

export const referrals: Referral[] = [
  {
    id: "paywise-500",
    service: "PayWise",
    initials: "PW",
    category: "finance",
    benefit: "₹500 CASHBACK",
    benefitType: "cashback",
    summary: "Get ₹500 after your first successful UPI payment of ₹100 or more.",
    details:
      "PayWise credits ₹500 into your wallet once you finish KYC and make one UPI payment of at least ₹100. The reward usually lands within 48 hours, and I get ₹250 as the referrer — so it genuinely helps both of us.",
    conditions: [
      "New users only, one reward per verified phone number",
      "Complete KYC within 7 days of signing up",
      "First payment must be ₹100 or more",
    ],
    code: "PAYWISE-ADI500",
    isLink: false,
    tags: ["UPI", "wallet", "cashback"],
    postedBy: p("aditya", "Aditya R.", "AR", 92),
    postedAgo: "2 hours ago",
    postedOn: "12 Aug 2026",
    copies: 1284,
    popularity: 98,
    trust: ["verified", "trusted"],
    expires: "30 Sep 2026",
    status: "active",
  },
  {
    id: "loomnote-free-month",
    service: "LoomNote",
    initials: "LN",
    category: "productivity",
    benefit: "1 MONTH FREE",
    benefitType: "free-month",
    summary: "Unlock one month of LoomNote Pro — unlimited notes, AI summaries, offline sync.",
    details:
      "Sign up with this link and Pro unlocks automatically for 30 days, no card needed up front. If you stay after the trial, I receive one free month too.",
    conditions: [
      "New workspaces only",
      "Card required after day 30",
      "Cannot stack with student plan",
    ],
    code: "https://loomnote.example/r/mira-pro",
    isLink: true,
    tags: ["notes", "AI", "SaaS"],
    postedBy: p("mira", "Mira K.", "MK", 88),
    postedAgo: "5 hours ago",
    postedOn: "12 Aug 2026",
    copies: 642,
    popularity: 91,
    trust: ["verified"],
    expires: "31 Dec 2026",
    status: "active",
  },
  {
    id: "bitecart-20",
    service: "BiteCart",
    initials: "BC",
    category: "food",
    benefit: "20% OFF",
    benefitType: "discount",
    summary: "Get 20% off your first three food orders, up to ₹150 per order.",
    details:
      "Apply the code at checkout. Works on the first three orders from any restaurant on BiteCart. Delivery fee is not discounted.",
    conditions: [
      "First-time BiteCart users",
      "Max ₹150 discount per order",
      "Not valid on groceries",
    ],
    code: "BITE20-NEHA",
    isLink: false,
    tags: ["delivery", "first order"],
    postedBy: p("neha", "Neha S.", "NS", 79),
    postedAgo: "1 day ago",
    postedOn: "11 Aug 2026",
    copies: 2210,
    popularity: 96,
    trust: ["trusted"],
    expires: "20 Aug 2026",
    status: "active",
  },
  {
    id: "skyhop-1000",
    service: "SkyHop",
    initials: "SH",
    category: "travel",
    benefit: "₹1,000 REWARD",
    benefitType: "reward",
    summary: "Earn ₹1,000 travel credit after completing your first booking.",
    details:
      "Book any flight or hotel worth ₹4,000+ and SkyHop drops ₹1,000 in travel credits into your account after check-in is complete.",
    conditions: [
      "Minimum booking value ₹4,000",
      "Credit expires 6 months after issue",
      "One per traveller",
    ],
    code: "SKYHOP-RVK1000",
    isLink: false,
    tags: ["flights", "hotels", "credit"],
    postedBy: p("ravi", "Ravi T.", "RT", 84),
    postedAgo: "1 day ago",
    postedOn: "11 Aug 2026",
    copies: 431,
    popularity: 82,
    trust: ["verified", "expiring"],
    expires: "25 Aug 2026",
    status: "active",
  },
  {
    id: "deploylane-credits",
    service: "DeployLane",
    initials: "DL",
    category: "developer",
    benefit: "$50 CREDITS",
    benefitType: "credits",
    summary: "Get $50 in hosting credits when you deploy your first project.",
    details:
      "Credits apply to compute, bandwidth and managed Postgres. They land after your first successful production deploy and are valid for 90 days.",
    conditions: ["New accounts only", "Credits valid 90 days", "Requires one production deploy"],
    code: "https://deploylane.example/invite/kabir",
    isLink: true,
    tags: ["hosting", "cloud", "postgres"],
    postedBy: p("kabir", "Kabir M.", "KM", 95),
    postedAgo: "2 days ago",
    postedOn: "10 Aug 2026",
    copies: 388,
    popularity: 87,
    trust: ["verified", "trusted"],
    expires: "31 Oct 2026",
    status: "active",
  },
  {
    id: "shopnest-300",
    service: "ShopNest",
    initials: "SN",
    category: "shopping",
    benefit: "₹300 OFF",
    benefitType: "discount",
    summary: "Flat ₹300 off your first order above ₹999 across fashion and home.",
    details: "One-time use per account. Stacks with sale prices but not with bank card offers.",
    conditions: ["Minimum cart ₹999", "One use per account", "Excludes electronics"],
    code: "NEST300-TARA",
    isLink: false,
    tags: ["fashion", "home"],
    postedBy: p("tara", "Tara B.", "TB", 71),
    postedAgo: "3 days ago",
    postedOn: "9 Aug 2026",
    copies: 903,
    popularity: 74,
    trust: ["new"],
    expires: "15 Sep 2026",
    status: "active",
  },
  {
    id: "learnloop-free-month",
    service: "LearnLoop",
    initials: "LL",
    category: "education",
    benefit: "1 MONTH FREE",
    benefitType: "free-month",
    summary: "One month of unlimited courses, including certification tracks.",
    details:
      "Covers every course in the catalogue plus one certificate attempt. Both of us get an extra week if you finish a course in month one.",
    conditions: ["New learners only", "Certificate attempt valid 60 days"],
    code: "LEARN-FREE-ISHA",
    isLink: false,
    tags: ["courses", "certification"],
    postedBy: p("isha", "Isha P.", "IP", 80),
    postedAgo: "3 days ago",
    postedOn: "9 Aug 2026",
    copies: 512,
    popularity: 69,
    trust: ["trusted"],
    expires: "01 Nov 2026",
    status: "active",
  },
  {
    id: "streamly-2months",
    service: "Streamly",
    initials: "ST",
    category: "entertainment",
    benefit: "2 MONTHS FREE",
    benefitType: "free-month",
    summary: "Two months of ad-free streaming on the standard plan.",
    details: "Invite benefit — you get two months, I get one. Works on annual and monthly plans.",
    conditions: ["New subscriptions only", "Standard plan", "Card required at signup"],
    code: "https://streamly.example/join/dev-arun",
    isLink: true,
    tags: ["streaming", "invite"],
    postedBy: p("arun", "Arun V.", "AV", 76),
    postedAgo: "4 days ago",
    postedOn: "8 Aug 2026",
    copies: 1876,
    popularity: 93,
    trust: ["trusted"],
    expires: "30 Nov 2026",
    status: "active",
  },
  {
    id: "vaultbank-750",
    service: "VaultBank",
    initials: "VB",
    category: "finance",
    benefit: "₹750 REWARD",
    benefitType: "reward",
    summary: "Open a zero-balance account and both of us get ₹750.",
    details:
      "Fully digital onboarding. Reward credits after your first ₹1,000 deposit stays for 30 days.",
    conditions: ["Aadhaar-based KYC", "₹1,000 must stay for 30 days", "Salary accounts excluded"],
    code: "VAULT-750-SANA",
    isLink: false,
    tags: ["bank", "zero balance"],
    postedBy: p("sana", "Sana Q.", "SQ", 90),
    postedAgo: "5 days ago",
    postedOn: "7 Aug 2026",
    copies: 745,
    popularity: 85,
    trust: ["verified"],
    expires: "31 Dec 2026",
    status: "active",
  },
  {
    id: "freshbasket-150",
    service: "FreshBasket",
    initials: "FB",
    category: "food",
    benefit: "₹150 OFF",
    benefitType: "discount",
    summary: "₹150 off your first two grocery orders above ₹499.",
    details: "Great for a first stock-up. Perishables included, no category exclusions.",
    conditions: ["Minimum ₹499", "Valid on first two orders"],
    code: "FRESH150-DEV",
    isLink: false,
    tags: ["groceries"],
    postedBy: p("dev", "Dev N.", "DN", 68),
    postedAgo: "6 days ago",
    postedOn: "6 Aug 2026",
    copies: 356,
    popularity: 58,
    trust: ["new"],
    expires: "22 Aug 2026",
    status: "active",
  },
  {
    id: "pixelforge-40",
    service: "PixelForge",
    initials: "PF",
    category: "productivity",
    benefit: "40% OFF",
    benefitType: "discount",
    summary: "40% off the first year of the design suite for new teams.",
    details: "Applies to teams of up to 10 seats. The discount holds for the full first year.",
    conditions: ["New teams only", "Up to 10 seats", "Annual billing"],
    code: "FORGE40-MIRA",
    isLink: false,
    tags: ["design", "team"],
    postedBy: p("mira", "Mira K.", "MK", 88),
    postedAgo: "1 week ago",
    postedOn: "5 Aug 2026",
    copies: 214,
    popularity: 61,
    trust: ["trusted"],
    expires: "30 Sep 2026",
    status: "active",
  },
  {
    id: "commuta-5rides",
    service: "Commuta",
    initials: "CM",
    category: "travel",
    benefit: "5 FREE RIDES",
    benefitType: "reward",
    summary: "Five rides up to ₹100 each in your first two weeks.",
    details: "Rides apply automatically at checkout. City coverage is limited to metros right now.",
    conditions: ["New riders", "Max ₹100 per ride", "Metro cities only"],
    code: "COMMUTA-5-RAVI",
    isLink: false,
    tags: ["cabs", "city"],
    postedBy: p("ravi", "Ravi T.", "RT", 84),
    postedAgo: "1 week ago",
    postedOn: "5 Aug 2026",
    copies: 622,
    popularity: 72,
    trust: ["verified"],
    expires: "18 Aug 2026",
    status: "active",
  },
  {
    id: "codepilot-3months",
    service: "CodePilot",
    initials: "CP",
    category: "developer",
    benefit: "3 MONTHS FREE",
    benefitType: "free-month",
    summary: "Three months of the AI pair-programming plan for individual devs.",
    details: "Student and open-source maintainers get an extra three months on top.",
    conditions: ["Individual plans only", "Verify GitHub account"],
    code: "https://codepilot.example/r/kabir3",
    isLink: true,
    tags: ["AI", "coding"],
    postedBy: p("kabir", "Kabir M.", "KM", 95),
    postedAgo: "1 week ago",
    postedOn: "4 Aug 2026",
    copies: 1102,
    popularity: 94,
    trust: ["verified", "trusted"],
    expires: "31 Dec 2026",
    status: "active",
  },
  {
    id: "tuneup-1000",
    service: "TuneUp Music",
    initials: "TU",
    category: "entertainment",
    benefit: "₹1,000 REWARD",
    benefitType: "reward",
    summary: "Family plan invite — join and get ₹1,000 back after three months.",
    details: "Both members receive the reward once three consecutive payments clear.",
    conditions: ["Family plan only", "Three consecutive payments"],
    code: "TUNEUP-FAM-NEHA",
    isLink: false,
    tags: ["music", "family plan"],
    postedBy: p("neha", "Neha S.", "NS", 79),
    postedAgo: "2 weeks ago",
    postedOn: "30 Jul 2026",
    copies: 289,
    popularity: 55,
    trust: ["new"],
    expires: "30 Sep 2026",
    status: "active",
  },
  {
    id: "examspark-25",
    service: "ExamSpark",
    initials: "ES",
    category: "education",
    benefit: "25% OFF",
    benefitType: "discount",
    summary: "25% off any test-prep track, including live doubt sessions.",
    details: "Best used on the annual track. Refundable within 7 days if you change your mind.",
    conditions: ["Annual tracks only", "7-day refund window"],
    code: "SPARK25-ISHA",
    isLink: false,
    tags: ["test prep"],
    postedBy: p("isha", "Isha P.", "IP", 80),
    postedAgo: "2 weeks ago",
    postedOn: "29 Jul 2026",
    copies: 176,
    popularity: 48,
    trust: [],
    expires: "10 Sep 2026",
    status: "active",
  },
  {
    id: "kartify-500",
    service: "Kartify",
    initials: "KF",
    category: "shopping",
    benefit: "₹500 CREDITS",
    benefitType: "credits",
    summary: "₹500 store credit after your first delivered order.",
    details: "Credit is added once the return window closes, so about 10 days after delivery.",
    conditions: ["First delivered order", "Credit valid 60 days"],
    code: "KART-500-TARA",
    isLink: false,
    tags: ["marketplace", "credit"],
    postedBy: p("tara", "Tara B.", "TB", 71),
    postedAgo: "2 weeks ago",
    postedOn: "28 Jul 2026",
    copies: 508,
    popularity: 66,
    trust: ["trusted"],
    expires: "30 Sep 2026",
    status: "active",
  },
  {
    id: "ledgerly-2months",
    service: "Ledgerly",
    initials: "LG",
    category: "finance",
    benefit: "2 MONTHS FREE",
    benefitType: "free-month",
    summary: "Two months free on the freelancer invoicing plan.",
    details: "Includes GST invoices, payment reminders and one connected bank account.",
    conditions: ["New accounts", "Freelancer plan only"],
    code: "LEDGER-2FREE-SANA",
    isLink: false,
    tags: ["invoicing", "freelance"],
    postedBy: p("sana", "Sana Q.", "SQ", 90),
    postedAgo: "3 weeks ago",
    postedOn: "24 Jul 2026",
    copies: 143,
    popularity: 44,
    trust: ["verified"],
    expires: "31 Oct 2026",
    status: "active",
  },
  {
    id: "roamstay-800",
    service: "RoamStay",
    initials: "RS",
    category: "travel",
    benefit: "₹800 OFF",
    benefitType: "discount",
    summary: "₹800 off your first two-night stay at any partner property.",
    details: "Works best on weekday stays. Cancellation keeps the code alive for one more try.",
    conditions: ["Minimum two nights", "Partner properties only"],
    code: "ROAM800-ARUN",
    isLink: false,
    tags: ["stays", "weekend"],
    postedBy: p("arun", "Arun V.", "AV", 76),
    postedAgo: "3 weeks ago",
    postedOn: "22 Jul 2026",
    copies: 267,
    popularity: 52,
    trust: [],
    expires: "16 Aug 2026",
    status: "past",
  },
  {
    id: "focusflow-credits",
    service: "FocusFlow",
    initials: "FF",
    category: "productivity",
    benefit: "₹600 CREDITS",
    benefitType: "credits",
    summary: "₹600 in credits toward any focus-timer team plan.",
    details:
      "Credits apply at the next billing cycle and never expire while the team stays active.",
    conditions: ["Teams of 3+", "Applied at next billing cycle"],
    code: "FLOW600-ADI",
    isLink: false,
    tags: ["focus", "teams"],
    postedBy: p("aditya", "Aditya R.", "AR", 92),
    postedAgo: "3 weeks ago",
    postedOn: "21 Jul 2026",
    copies: 98,
    popularity: 39,
    trust: ["new"],
    expires: "30 Nov 2026",
    status: "active",
  },
  {
    id: "queryhub-free-month",
    service: "QueryHub",
    initials: "QH",
    category: "developer",
    benefit: "1 MONTH FREE",
    benefitType: "free-month",
    summary: "One month of the managed analytics database, no card required.",
    details: "Includes 50GB storage and unlimited read replicas during the trial month.",
    conditions: ["One trial per organisation", "50GB storage cap"],
    code: "https://queryhub.example/r/dev-n",
    isLink: true,
    tags: ["database", "analytics"],
    postedBy: p("dev", "Dev N.", "DN", 68),
    postedAgo: "4 weeks ago",
    postedOn: "17 Jul 2026",
    copies: 121,
    popularity: 41,
    trust: [],
    expires: "31 Aug 2026",
    status: "past",
  },
  {
    id: "snackbox-100",
    service: "SnackBox",
    initials: "SB",
    category: "food",
    benefit: "₹100 OFF",
    benefitType: "discount",
    summary: "₹100 off the first monthly snack subscription box.",
    details: "Skip or cancel anytime. Referrer gets a free box after your second month.",
    conditions: ["First box only", "Subscription required"],
    code: "SNACK100-NEHA",
    isLink: false,
    tags: ["subscription", "snacks"],
    postedBy: p("neha", "Neha S.", "NS", 79),
    postedAgo: "1 month ago",
    postedOn: "14 Jul 2026",
    copies: 187,
    popularity: 36,
    trust: [],
    expires: "12 Aug 2026",
    status: "past",
  },
  {
    id: "cloudcase-200",
    service: "CloudCase",
    initials: "CC",
    category: "shopping",
    benefit: "₹200 OFF",
    benefitType: "discount",
    summary: "₹200 off phone cases and accessories over ₹699.",
    details: "Small but reliable — works on almost every product page except limited drops.",
    conditions: ["Minimum ₹699", "Excludes limited drops"],
    code: "CASE200-TARA",
    isLink: false,
    tags: ["accessories"],
    postedBy: p("tara", "Tara B.", "TB", 71),
    postedAgo: "1 month ago",
    postedOn: "12 Jul 2026",
    copies: 244,
    popularity: 33,
    trust: [],
    expires: "31 Aug 2026",
    status: "active",
  },
  {
    id: "playarcade-credits",
    service: "PlayArcade",
    initials: "PA",
    category: "entertainment",
    benefit: "500 CREDITS",
    benefitType: "credits",
    summary: "500 in-game credits when a friend invites you to the arcade pass.",
    details: "Credits work across every title in the pass and land instantly on signup.",
    conditions: ["New players only", "Arcade pass required"],
    code: "ARCADE-500-ARUN",
    isLink: false,
    tags: ["gaming", "invite"],
    postedBy: p("arun", "Arun V.", "AV", 76),
    postedAgo: "1 month ago",
    postedOn: "10 Jul 2026",
    copies: 331,
    popularity: 47,
    trust: ["trusted"],
    expires: "31 Dec 2026",
    status: "active",
  },
  {
    id: "tutorpair-free-class",
    service: "TutorPair",
    initials: "TP",
    category: "education",
    benefit: "3 FREE CLASSES",
    benefitType: "reward",
    summary: "Three free one-on-one classes in any subject for new students.",
    details: "Pick any tutor rated 4.5 or above. Classes must be used within 30 days.",
    conditions: ["New students", "Use within 30 days"],
    code: "TUTOR3-ISHA",
    isLink: false,
    tags: ["tutoring", "1:1"],
    postedBy: p("isha", "Isha P.", "IP", 80),
    postedAgo: "1 month ago",
    postedOn: "8 Jul 2026",
    copies: 159,
    popularity: 42,
    trust: ["new"],
    expires: "30 Sep 2026",
    status: "active",
  },
];

export const getReferral = (id: string) => referrals.find((r) => r.id === id);

export const similarTo = (r: Referral, n = 3) =>
  referrals.filter((x) => x.id !== r.id && x.category === r.category).slice(0, n);

export const trustLabel: Record<Trust, string> = {
  verified: "Verified",
  trusted: "Community trusted",
  new: "New",
  expiring: "Expiring soon",
};

export const maskCode = (code: string) => {
  if (code.length <= 6) return "••••••";
  return code.slice(0, 4) + "•".repeat(Math.min(14, code.length - 6)) + code.slice(-2);
};
